#!/usr/bin/env python3
"""Align an adopted project's tasks/QUEUE.md usage text with closure ownership.

Dry run by default: prints a unified diff per project. Pass --apply to write.
Only known bullets and sentences are replaced; anything else is left alone and
reported. Never stages or commits.
"""
import argparse
import difflib
import re
import shutil
import subprocess
import sys
from pathlib import Path

LEAN_BULLETS = {
    "Execution": (
        "- **Execution**: The developer assigns a specific `[ ]` task; agents do not\n"
        "  select work autonomously.\n"
    ),
    "Update": (
        "- **Update**: Task branches do not edit this file. A row keeps `[ ]` until\n"
        "  `meridian worktree integrate stage` sets `[x]` on the merged candidate;\n"
        "  in-progress state is derived from the task branch, its registered worktree,\n"
        "  and the unarchived task record.\n"
    ),
    "Task-file archive": (
        "- **Task-file archive**: The task branch moves its completed task file to\n"
        "  `tasks/done/`.\n"
    ),
    "Queue archive": (
        "- **Queue archive**: `integrate stage` moves the rows of a fully closed phase\n"
        "  to `tasks/QUEUE_ARCHIVE.md` instead of accumulating them here.\n"
    ),
}

GOVERNED_CHOOSE = re.compile(
    r"Choose the highest-priority queued task whose dependencies are (?:all )?accepted\."
    r"(?: Break ties by (?P<ties>[^.\n]*)\.)?"
)
GOVERNED_CHOOSE_NEW = (
    "The developer assigns a specific queued task; agents do not select work autonomously."
)


def governed_choose_replacement(match: re.Match) -> str:
    ties = match.group("ties")
    if not ties:
        return GOVERNED_CHOOSE_NEW
    return (
        f"{GOVERNED_CHOOSE_NEW} When asked to recommend one, rank by priority, then by {ties}."
    )


GOVERNED_ARCHIVING = re.compile(
    r"\*\*Archiving\.\*\* Once this table grows large enough.*?only where it is read from\.\n",
    re.DOTALL,
)
GOVERNED_ARCHIVING_NEW = (
    "**Archiving.** `meridian worktree integrate stage` moves closed rows to\n"
    "`tasks/QUEUE_ARCHIVE.md` on the merged candidate tree, keeping this table to\n"
    "active and queued work only. `ACCEPTED` rows still satisfy dependencies from\n"
    "their archived location; moving a row changes only where it is read from.\n"
)


def bullet_pattern(key: str) -> re.Pattern:
    # A bullet line plus its indented continuation lines.
    return re.compile(rf"^- \*\*{re.escape(key)}\*\*:.*\n(?:[ \t]+\S.*\n)*", re.MULTILINE)


def align(text: str) -> tuple[str, list[str]]:
    notes = []
    if "## How to use this queue" in text:
        for key, new in LEAN_BULLETS.items():
            pattern = bullet_pattern(key)
            if pattern.search(text):
                text = pattern.sub(lambda _m, n=new: n, text, count=1)
            else:
                notes.append(f"lean bullet not found: {key}")
    else:
        text, count = GOVERNED_CHOOSE.subn(governed_choose_replacement, text)
        if count:
            notes.append(f"selection sentence replaced {count} time(s)")
        else:
            notes.append("no selection sentence (nothing to change)")
        if GOVERNED_ARCHIVING.search(text):
            text = GOVERNED_ARCHIVING.sub(lambda _m: GOVERNED_ARCHIVING_NEW, text, count=1)
        else:
            notes.append("no seed Archiving paragraph (nothing to change)")
    return text, notes


def resolve_queue(project: Path, meridian: str | None) -> Path:
    """Ask the Meridian CLI for the declared queue; fall back to tasks/QUEUE.md."""
    candidates = [meridian] if meridian else []
    found = shutil.which("meridian")
    if found:
        candidates.append(found)
    for executable in candidates:
        try:
            result = subprocess.run(
                [executable, "locations", "--project", str(project), "--field", "queue"],
                capture_output=True, text=True, check=False, timeout=30,
            )
        except OSError:
            continue
        relative = result.stdout.strip().splitlines()
        if result.returncode == 0 and relative:
            return project / relative[-1].strip()
    return project / "tasks" / "QUEUE.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("projects", nargs="+", type=Path)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--meridian", help="path to bin/meridian used to resolve the queue location")
    args = parser.parse_args()
    status = 0
    for project in args.projects:
        project = project.resolve()
        queue = resolve_queue(project, args.meridian)
        if not queue.is_file():
            print(f"== {project}: no queue at {queue.relative_to(project)}, skipped")
            status = 1
            continue
        old = queue.read_text(encoding="utf-8")
        new, notes = align(old)
        print(f"== {project} ({queue.relative_to(project)})")
        for note in notes:
            print(f"   note: {note}")
        if new == old:
            print("   no change")
            continue
        sys.stdout.writelines(difflib.unified_diff(
            old.splitlines(keepends=True), new.splitlines(keepends=True),
            f"a/{queue.relative_to(project)}", f"b/{queue.relative_to(project)}"))
        if args.apply:
            queue.write_text(new, encoding="utf-8")
            print("   written (not staged or committed)")
    return status


if __name__ == "__main__":
    sys.exit(main())
